name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  # schedule:
  #   - cron: '*/5 * * * *'

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/playwright:v1.43.1-jammy
      options: --ipc=host

    steps:
      - name: Git clone
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run Playwright tests
        run: npx playwright test --project chromium --grep '@githubAction'

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
